name: base
channels:
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - conda-forge
  - defaults
dependencies:
  - anyio
  - aom
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - attrs
  - backcall
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - blas
  - bleach
  - boltons
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - comm
  - conda
  - conda-package-handling
  - conda-package-streaming
  - contourpy
  - cryptography
  - cycler
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - executing
  - expat
  - ffmpeg
  - filelock
  - flit-core
  - fmt
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-anaconda
  - fonts-conda-ecosystem
  - fonttools
  - freetype
  - gettext
  - giflib
  - gmp
  - gmpy2
  - gnutls
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - jsonpatch
  - jsonpointer
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab_pygments
  - jupyterlab_widgets
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - lerc
  - libarchive
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgfortran
  - libgfortran5
  - libiconv
  - libidn2
  - liblapack
  - libmamba
  - libmambapy
  - libnghttp2
  - libopenblas
  - libopus
  - libpng
  - libsodium
  - libsolv
  - libsqlite
  - libssh2
  - libtasn1
  - libtiff
  - libunistring
  - libvpx
  - libwebp
  - libwebp-base
  - libxml2
  - libzlib
  - llvm-openmp
  - lz4-c
  - lzo
  - mamba
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mpc
  - mpfr
  - munkres
  - nbclassic
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nbformat
  - ncurses
  - nest-asyncio
  - nettle
  - networkx
  - notebook
  - notebook-shim
  - numpy
  - numpy-base
  - openh264
  - openssl
  - p11-kit
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - patsy
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkgutil-resolve-name
  - platformdirs
  - pluggy
  - pooch
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pybind11-abi
  - pycosat
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-tzdata
  - python_abi
  - pytorch
  - pytz
  - pyyaml
  - pyzmq
  - readline
  - reproc
  - reproc-cpp
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - ruamel.yaml
  - ruamel.yaml.clib
  - scipy
  - seaborn
  - seaborn-base
  - send2trash
  - setuptools
  - six
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - statsmodels
  - svt-av1
  - sympy
  - terminado
  - tinycss2
  - tk
  - toolz
  - torchaudio
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - unicodedata2
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - x264
  - x265
  - xz
  - yaml
  - yaml-cpp
  - zeromq
  - zipp
  - zlib
  - zstandard
  - zstd
  - pip:
      - mpmath
