name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio
  - aom
  - appnope
  - archspec
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - asttokens
  - async-lru
  - attrs
  - babel
  - beautifulsoup4
  - bleach
  - boltons
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cached-property
  - cached_property
  - cairo
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - comm
  - conda
  - conda-libmamba-solver
  - conda-package-handling
  - conda-package-streaming
  - contourpy
  - cpython
  - cycler
  - dav1d
  - debugpy
  - decorator
  - defusedxml
  - distro
  - entrypoints
  - exceptiongroup
  - executing
  - expat
  - ffmpeg
  - filelock
  - fmt
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - fqdn
  - freetype
  - fribidi
  - frozendict
  - fsspec
  - gmp
  - gmpy2
  - graphite2
  - h11
  - h2
  - harfbuzz
  - hdf5
  - hpack
  - httpcore
  - httpx
  - hyperframe
  - icu
  - idna
  - imath
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - ipykernel
  - ipython
  - ipywidgets
  - isoduration
  - jasper
  - jedi
  - jinja2
  - json5
  - jsonpatch
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jsonschema-with-format-nongpl
  - jupyter
  - jupyter-lsp
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - lerc
  - libabseil
  - libaec
  - libarchive
  - libasprintf
  - libass
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libexpat
  - libffi
  - libgettextpo
  - libgfortran
  - libgfortran5
  - libglib
  - libhwloc
  - libiconv
  - libintl
  - libjpeg-turbo
  - liblapack
  - liblapacke
  - libmamba
  - libmambapy
  - libnghttp2
  - libopenblas
  - libopencv
  - libopenvino
  - libopenvino-arm-cpu-plugin
  - libopenvino-auto-batch-plugin
  - libopenvino-auto-plugin
  - libopenvino-hetero-plugin
  - libopenvino-ir-frontend
  - libopenvino-onnx-frontend
  - libopenvino-paddle-frontend
  - libopenvino-pytorch-frontend
  - libopenvino-tensorflow-frontend
  - libopenvino-tensorflow-lite-frontend
  - libopus
  - libpng
  - libprotobuf
  - libsodium
  - libsolv
  - libsqlite
  - libssh2
  - libtiff
  - libtorch
  - libuv
  - libvpx
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - llvm-openmp
  - lz4-c
  - lzo
  - mamba
  - markupsafe
  - matplotlib-base
  - matplotlib-inline
  - menuinst
  - mistune
  - mpc
  - mpfr
  - mpmath
  - munkres
  - nbclient
  - nbconvert-core
  - nbformat
  - ncurses
  - nest-asyncio
  - networkx
  - nomkl
  - notebook
  - notebook-shim
  - numpy
  - opencv
  - openexr
  - openh264
  - openjpeg
  - openssl
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - parso
  - patsy
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - pkgutil-resolve-name
  - platformdirs
  - pluggy
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pugixml
  - pure_eval
  - py-cpuinfo
  - py-opencv
  - pybind11-abi
  - pycosat
  - pycparser
  - pygments
  - pyparsing
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-tzdata
  - python_abi
  - pytorch
  - pytz
  - pyyaml
  - pyzmq
  - qhull
  - readline
  - referencing
  - reproc
  - reproc-cpp
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rpds-py
  - ruamel.yaml
  - ruamel.yaml.clib
  - scipy
  - seaborn
  - seaborn-base
  - send2trash
  - setuptools
  - six
  - sleef
  - snappy
  - sniffio
  - soupsieve
  - stack_data
  - statsmodels
  - svt-av1
  - sympy
  - tbb
  - terminado
  - tinycss2
  - tk
  - tomli
  - tornado
  - tqdm
  - traitlets
  - truststore
  - types-python-dateutil
  - typing-extensions
  - typing_extensions
  - typing_utils
  - tzdata
  - ultralytics
  - uri-template
  - urllib3
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - x264
  - x265
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml
  - yaml-cpp
  - zeromq
  - zipp
  - zlib
  - zstandard
  - zstd
