name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aom
  - appnope
  - archspec
  - asttokens
  - backcall
  - backports
  - backports.functools_lru_cache
  - boltons
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - comm
  - conda
  - conda-libmamba-solver
  - conda-package-handling
  - conda-package-streaming
  - contourpy
  - cryptography
  - cycler
  - dav1d
  - debugpy
  - decorator
  - dill
  - distro
  - exceptiongroup
  - executing
  - expat
  - ffmpeg
  - filelock
  - fmt
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - fribidi
  - frozendict
  - fsspec
  - gettext
  - gettext-tools
  - gmp
  - gmpy2
  - gnutls
  - graphite2
  - h2
  - harfbuzz
  - hpack
  - hyperframe
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - ipykernel
  - ipython
  - jedi
  - jinja2
  - jpeg
  - jsonpatch
  - jsonpointer
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - lerc
  - libabseil
  - libarchive
  - libasprintf
  - libasprintf-devel
  - libass
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libcxx
  - libdav1d7
  - libdeflate
  - libedit
  - libev
  - libexpat
  - libffi
  - libgettextpo
  - libgettextpo-devel
  - libgfortran
  - libgfortran5
  - libglib
  - libhwloc
  - libiconv
  - libidn2
  - libintl
  - libintl-devel
  - libjpeg-turbo
  - liblapack
  - libmamba
  - libmambapy
  - libnghttp2
  - libopenblas
  - libopenvino
  - libopenvino-arm-cpu-plugin
  - libopenvino-auto-batch-plugin
  - libopenvino-auto-plugin
  - libopenvino-hetero-plugin
  - libopenvino-ir-frontend
  - libopenvino-onnx-frontend
  - libopenvino-paddle-frontend
  - libopenvino-pytorch-frontend
  - libopenvino-tensorflow-frontend
  - libopenvino-tensorflow-lite-frontend
  - libopus
  - libpng
  - libprotobuf
  - libsodium
  - libsolv
  - libsqlite
  - libssh2
  - libtasn1
  - libtiff
  - libtorch
  - libunistring
  - libuv
  - libvpx
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - llvm-openmp
  - lz4-c
  - lzo
  - mamba
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - menuinst
  - meson
  - mpc
  - mpfr
  - mpmath
  - multiprocess
  - munkres
  - ncurses
  - nest-asyncio
  - nettle
  - networkx
  - ninja
  - nomkl
  - numpy
  - openh264
  - openjpeg
  - openssl
  - p11-kit
  - packaging
  - pandas
  - parso
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pixman
  - platformdirs
  - pluggy
  - pooch
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pugixml
  - pure_eval
  - pybind11-abi
  - pycosat
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pysocks
  - python
  - python-dateutil
  - python-tzdata
  - python_abi
  - pytorch
  - pytz
  - pyyaml
  - pyzmq
  - readline
  - reproc
  - reproc-cpp
  - requests
  - ruamel.yaml
  - ruamel.yaml.clib
  - scipy
  - setuptools
  - six
  - sleef
  - snappy
  - stack_data
  - svt-av1
  - sympy
  - tbb
  - tk
  - toolz
  - torchaudio
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - truststore
  - typing-extensions
  - typing_extensions
  - tzdata
  - unicodedata2
  - urllib3
  - wcwidth
  - wheel
  - x264
  - x265
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml
  - yaml-cpp
  - zeromq
  - zipp
  - zlib
  - zstandard
  - zstd
  - pip:
      - pip
