name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - accessible-pygments
  - aiofiles
  - aiosqlite
  - alabaster
  - anyio
  - aom
  - appdirs
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - attrs
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - blas
  - blas-devel
  - bleach
  - boltons
  - bottleneck
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - click
  - colorama
  - comm
  - conda
  - conda-package-handling
  - conda-package-streaming
  - contourpy
  - cryptography
  - cycler
  - dataclasses
  - debugpy
  - decorator
  - defusedxml
  - docutils
  - entrypoints
  - executing
  - expat
  - ffmpeg
  - filelock
  - flit-core
  - fmt
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - gettext
  - giflib
  - glib
  - glib-tools
  - gmp
  - gmpy2
  - gnutls
  - greenlet
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - imagesize
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - json5
  - jsonpatch
  - jsonpointer
  - jsonschema
  - jupyter
  - jupyter-book
  - jupyter-cache
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_fileid
  - jupyter_server_terminals
  - jupyter_server_ydoc
  - jupyter_ydoc
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kiwisolver
  - krb5
  - lame
  - latexcodec
  - lcms2
  - lerc
  - libarchive
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libclang
  - libclang13
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libexpat
  - libffi
  - libgfortran
  - libgfortran5
  - libglib
  - libiconv
  - libidn2
  - liblapack
  - liblapacke
  - libllvm12
  - libllvm14
  - libmamba
  - libmambapy
  - libnghttp2
  - libogg
  - libopenblas
  - libopus
  - libpng
  - libpq
  - libprotobuf
  - libsodium
  - libsolv
  - libsqlite
  - libssh2
  - libtasn1
  - libtiff
  - libunistring
  - libvorbis
  - libvpx
  - libwebp
  - libwebp-base
  - libxcb
  - libxml2
  - libxslt
  - libzlib
  - linkify-it-py
  - llvm-openmp
  - lxml
  - lz4-c
  - lzo
  - mamba
  - markdown-it-py
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mdit-py-plugins
  - mdurl
  - mistune
  - mpc
  - mpfr
  - mpmath
  - munkres
  - mysql-common
  - mysql-libs
  - myst-nb
  - myst-parser
  - nbclassic
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nbformat
  - ncurses
  - nest-asyncio
  - nettle
  - networkx
  - nomkl
  - notebook
  - notebook-shim
  - nspr
  - nss
  - numexpr
  - numpy
  - numpy-base
  - openblas
  - openblas-devel
  - openh264
  - openjpeg
  - openssl
  - p11-kit
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - patsy
  - pcre
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkgutil-resolve-name
  - platformdirs
  - pluggy
  - ply
  - pooch
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pybind11-abi
  - pybtex
  - pybtex-docutils
  - pycosat
  - pycparser
  - pydata-sphinx-theme
  - pygments
  - pygwalker
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-tzdata
  - python_abi
  - pytorch
  - pytz
  - pyyaml
  - pyzmq
  - qt-main
  - qt-webengine
  - qtconsole
  - qtconsole-base
  - qtpy
  - qtwebkit
  - readline
  - reproc
  - reproc-cpp
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - ruamel.yaml
  - ruamel.yaml.clib
  - scipy
  - seaborn
  - seaborn-base
  - send2trash
  - setuptools
  - sip
  - six
  - sleef
  - sniffio
  - snowballstemmer
  - soupsieve
  - sphinx
  - sphinx-book-theme
  - sphinx-comments
  - sphinx-copybutton
  - sphinx-design
  - sphinx-external-toc
  - sphinx-jupyterbook-latex
  - sphinx-multitoc-numbering
  - sphinx-thebe
  - sphinx-togglebutton
  - sphinxcontrib-applehelp
  - sphinxcontrib-bibtex
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sqlalchemy
  - sqlite
  - stack_data
  - statsmodels
  - svt-av1
  - sympy
  - tabulate
  - terminado
  - tinycss2
  - tk
  - toml
  - tomli
  - toolz
  - torchaudio
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - uc-micro-py
  - unicodedata2
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - x264
  - x265
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - y-py
  - yaml
  - yaml-cpp
  - ypy-websocket
  - zeromq
  - zipp
  - zlib
  - zstandard
  - zstd
  - pip:
      - pyqt5-sip
