name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - boltons
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - click
  - colorama
  - conda
  - conda-package-handling
  - conda-package-streaming
  - cryptography
  - flask
  - flask_cors
  - fmt
  - icu
  - idna
  - importlib-metadata
  - itsdangerous
  - jinja2
  - jsonpatch
  - jsonpointer
  - krb5
  - libarchive
  - libcurl
  - libcxx
  - libedit
  - libev
  - libffi
  - libiconv
  - libmamba
  - libmambapy
  - libnghttp2
  - libsolv
  - libsqlite
  - libssh2
  - libxml2
  - libzlib
  - lz4-c
  - lzo
  - mamba
  - markupsafe
  - ncurses
  - openssl
  - packaging
  - pip
  - pluggy
  - pybind11-abi
  - pycosat
  - pycparser
  - pyopenssl
  - pysocks
  - python
  - python_abi
  - readline
  - reproc
  - reproc-cpp
  - requests
  - ruamel.yaml
  - ruamel.yaml.clib
  - setuptools
  - six
  - tk
  - toolz
  - tqdm
  - tzdata
  - urllib3
  - werkzeug
  - wheel
  - xz
  - yaml-cpp
  - zipp
  - zstandard
  - zstd
  - pip:
      - anyio
      - asgiref
      - diskcache
      - falcon
      - fastapi
      - fastdeploy
      - fastdeploy-python
      - fastdeploy-tools
      - gevent
      - greenlet
      - gunicorn
      - h11
      - numpy
      - opencv-python
      - pydantic
      - pyyaml
      - sniffio
      - starlette
      - typing-extensions
      - ujson
      - uvicorn
      - zope-event
      - zope-interface
