name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aom
  - boltons
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - conda
  - conda-package-handling
  - conda-package-streaming
  - cryptography
  - expat
  - ffmpeg
  - filelock
  - fmt
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - freetype
  - fribidi
  - gettext
  - gmp
  - gmpy2
  - gnutls
  - graphite2
  - harfbuzz
  - icu
  - idna
  - jinja2
  - jpeg
  - jsonpatch
  - jsonpointer
  - krb5
  - lame
  - lcms2
  - lerc
  - libarchive
  - libass
  - libblas
  - libcblas
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libexpat
  - libffi
  - libgfortran
  - libgfortran5
  - libglib
  - libiconv
  - libidn2
  - liblapack
  - libmamba
  - libmambapy
  - libnghttp2
  - libopenblas
  - libopus
  - libpng
  - libsolv
  - libsqlite
  - libssh2
  - libtasn1
  - libtiff
  - libunistring
  - libvpx
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - llvm-openmp
  - lz4-c
  - lzo
  - mamba
  - markupsafe
  - mpc
  - mpfr
  - mpmath
  - ncurses
  - nettle
  - networkx
  - numpy
  - openh264
  - openjpeg
  - openssl
  - p11-kit
  - packaging
  - pcre2
  - pillow
  - pip
  - pixman
  - pluggy
  - pthread-stubs
  - pybind11-abi
  - pycosat
  - pycparser
  - pyopenssl
  - pysocks
  - python
  - python_abi
  - pytorch
  - readline
  - reproc
  - reproc-cpp
  - requests
  - ruamel.yaml
  - ruamel.yaml.clib
  - setuptools
  - svt-av1
  - sympy
  - tk
  - toolz
  - torchaudio
  - torchvision
  - tqdm
  - typing_extensions
  - tzdata
  - urllib3
  - wheel
  - x264
  - x265
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml-cpp
  - zlib
  - zstandard
  - zstd
