* Tested Repositories
** [[https://pytorch.org][PyTorch]]
由 Meta AI(Facebook) 人工智能研究小组开发的一种基于 Lua 编写的 Torch 库的 Python 实现的深度学习库。

** [[https://github.com/WolframResearch/WolframLanguageForJupyter][Wolfram Language For Jupyter]]
Jupyter provides a protocol (ZMQ) to connect their notebooks to various languages. This project defines a Wolfram Language kernel which can be used in Jupyter notebooks.

* Untested Repositories
** [[https://github.com/Significant-Gravitas/Auto-GPT][Auto-GPT]]
它是一个实验性的开源应用程序，展示了 GPT-4 语言模型的功能。该程序由 GPT-4 驱动，可以自主实现用户设定的任何目标。

** [[https://github.com/Vision-CAIR/MiniGPT-4][MiniGPT]]
MiniGPT-4: Enhancing Vision-language Understanding with Advanced Large Language Models.

** [[https://github.com/OpenLMLab/MOSS][MOSS]] 
MOSS 是复旦大学开源的一个支持中英双语和多种插件的开源对话语言模型，moss-moon 系列模型具有160亿参数，在 FP16 精度下可在单张 A100/A800 或两张3090显卡运行，在 INT4/8 精度下可在单张3090显卡运行。MOSS 基座语言模型在约七千亿中英文以及代码单词上预训练得到，后续经过对话指令微调、插件增强学习和人类偏好训练具备多轮对话能力及使用多种插件的能力。

** [[https://github.com/Kanaries/pygwalker][pygwalker]]
A Python Library for Exploratory Data Analysis with Visualization.

** [[https://github.com/mlc-ai/web-llm][web-llm]]
This project brings large-language model and LLM-based chatbot to web browsers. 
